// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/meal_planner/data/models/meal_plan_record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8616877986498337850),
    name: 'MealPlanRecord',
    lastPropertyId: const obx_int.IdUid(8, 1744127614194598046),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7505541655811137724),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5620192906047319500),
        name: 'createdAtIso',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2203373767501295908),
        name: 'goal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3705851763914032473),
        name: 'dailyCalories',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5204091351553057396),
        name: 'macrosJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 784295650686667801),
        name: 'mealsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2561077897243019841),
        name: 'shoppingListJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1744127614194598046),
        name: 'userInputJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 8616877986498337850),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MealPlanRecord: obx_int.EntityDefinition<MealPlanRecord>(
      model: _entities[0],
      toOneRelations: (MealPlanRecord object) => [],
      toManyRelations: (MealPlanRecord object) => {},
      getId: (MealPlanRecord object) => object.id,
      setId: (MealPlanRecord object, int id) {
        object.id = id;
      },
      objectToFB: (MealPlanRecord object, fb.Builder fbb) {
        final createdAtIsoOffset = fbb.writeString(object.createdAtIso);
        final goalOffset = fbb.writeString(object.goal);
        final macrosJsonOffset = fbb.writeString(object.macrosJson);
        final mealsJsonOffset = fbb.writeString(object.mealsJson);
        final shoppingListJsonOffset = fbb.writeString(object.shoppingListJson);
        final userInputJsonOffset = fbb.writeString(object.userInputJson);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, createdAtIsoOffset);
        fbb.addOffset(2, goalOffset);
        fbb.addInt64(3, object.dailyCalories);
        fbb.addOffset(4, macrosJsonOffset);
        fbb.addOffset(5, mealsJsonOffset);
        fbb.addOffset(6, shoppingListJsonOffset);
        fbb.addOffset(7, userInputJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final createdAtIsoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final goalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dailyCaloriesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final macrosJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final mealsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final shoppingListJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final userInputJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = MealPlanRecord(
          id: idParam,
          createdAtIso: createdAtIsoParam,
          goal: goalParam,
          dailyCalories: dailyCaloriesParam,
          macrosJson: macrosJsonParam,
          mealsJson: mealsJsonParam,
          shoppingListJson: shoppingListJsonParam,
          userInputJson: userInputJsonParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MealPlanRecord] entity fields to define ObjectBox queries.
class MealPlanRecord_ {
  /// See [MealPlanRecord.id].
  static final id = obx.QueryIntegerProperty<MealPlanRecord>(
    _entities[0].properties[0],
  );

  /// See [MealPlanRecord.createdAtIso].
  static final createdAtIso = obx.QueryStringProperty<MealPlanRecord>(
    _entities[0].properties[1],
  );

  /// See [MealPlanRecord.goal].
  static final goal = obx.QueryStringProperty<MealPlanRecord>(
    _entities[0].properties[2],
  );

  /// See [MealPlanRecord.dailyCalories].
  static final dailyCalories = obx.QueryIntegerProperty<MealPlanRecord>(
    _entities[0].properties[3],
  );

  /// See [MealPlanRecord.macrosJson].
  static final macrosJson = obx.QueryStringProperty<MealPlanRecord>(
    _entities[0].properties[4],
  );

  /// See [MealPlanRecord.mealsJson].
  static final mealsJson = obx.QueryStringProperty<MealPlanRecord>(
    _entities[0].properties[5],
  );

  /// See [MealPlanRecord.shoppingListJson].
  static final shoppingListJson = obx.QueryStringProperty<MealPlanRecord>(
    _entities[0].properties[6],
  );

  /// See [MealPlanRecord.userInputJson].
  static final userInputJson = obx.QueryStringProperty<MealPlanRecord>(
    _entities[0].properties[7],
  );
}
